#!/bin/sh


index=index.md
indextmp=index.md.tmp
readmecontent=readme-content.md
readme=README.md
tmp=tmp.md

# remove frontmatter
sed '1{/^---$/!q;};1,/^---$/d' $index > $indextmp

cat $indextmp > $tmp
echo "" >> $tmp
cat $readmecontent >> $tmp

rm $indextmp

readmesize=$(wc -c <$readme)
tmpsize=$(wc -c <$tmp)

if [ $readmesize -ne $tmpsize ]; then
    mv $tmp $readme
    echo "Updated README.md!"
    exit 1
fi

rm $tmp

exit 0
